### ISSUE TITLE
Bot actions are not working

### ISSUE THREAD

**Issue by Sam948-byte** [Ghost-8D/Ghost-8D#75]
cc @Ghost-8D
![Screenshot 2022-05-11 21 46 42](https://user-images.githubusercontent.com/66854780/167981994-fc42f431-f206-4d47-b37f-f5e181224ef7.png)
This happened.  Look like it's been happening for a while.

**Comment by Ghost-8D** [comment]
I know it's been a while but now the issues have been fixed. Apparently, GitHub has a limit of 21000 characters for yaml files, so I had to find a workaround.
